### ISSUE TITLE
Build first release for `com.v4ex.Spider`

### ISSUE THREAD

**Issue by v4ex-inc** [v4ex/com.v4ex.Spider#1]
# Requirements
<sub>**(Proposed by: @XL19860214, Reviewed by: @XL19860214, Endorsed by: @XL19860214)**</sub>
1. Modules: `Nest`, `Crawler`
2. Module `Nest`
2.1. It is the command center.
2.2. It accepts submission from `Crawler`.
2.3. It stores data.
2.4. It handles data requests.
2.5. It can dispatch new `Crawler`.
2.6. It can request status report from `Crawler` to even monitor all crawlers.
3. Module `Crawler`
3.1. It is an internet bot.
3.2. It start crawling by a URL.
3.3. It knows a way to get a new starting URL if interrupted by any mean.
3.4. It follows preset rules to do the data fetch and data process, then submit to the `Nest`.
3.5. It knows in what conditions to abandon the task.
3.6. It has protocol to communicate with the `Nest`.
3.7. It has protocol to identify and communicate with another `Crawler`.

# Planning
<sub>**(Proposed by: @XL19860214, Reviewed by: , Endorsed by: )**</sub>
1. Build the `Crawler` module.
1.1. Utilize curated lists as starting point.
1.2. Minimalist, only fetch until `</head>`, utilize social media sharing meta tags when possible.
1.3. Utilize 'etag' as often as possible.
1.4. After submitting new harvest to the `Nest`, the response **MUST** include datetime of added and submitter for the status of that record in the database, to help `Crawler` decide next step operation.
1.4.1. Abandon crawling for this path if it knows other `Crawler` is doing it.
1.4.2. Abandon crawling for this path if it knows it has already done enough.
2. Build the `Nest` module.
2.1. According to the requirements.

# Implementation
<sub>(**Contributed by: @XL19860214, Reviewed by: , Endorsed by: )**</sub>

## Tasks
- [x] 1. Collect enough information about Social Media Share <meta> tags.
- [x] 2. Make a list of news media websites which included Social Media Share <meta> tags.
- [x] 3. Test HTTP requests with Header field 'Range' to Web Server.
- [ ] 4. List of Search Engines bot User-Agent

## 1. Collect enough information about Social Media Share <meta> tags.

<details><summary>Details</summary>

- https://css-tricks.com/essential-meta-tags-social-media/
- https://www.kontentino.com/blog/social-media-meta-tags-a-complete-guide/

1. Facebook
1.1. https://developers.facebook.com/docs/sharing/webmasters/
2. Twitter
2.1. https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards
3. Google Product Advanced SEO
3.1. https://developers.google.com/search/docs/advanced/structured-data/product#json-ld

----------------------------------------
</details>

## 2. Make a list of news media websites which included Social Media Share <meta> tags.

<details><summary>Details</summary>

1. Sources
1.1. https://en.wikipedia.org/wiki/News_media_in_the_United_States
1.2. https://en.wikipedia.org/wiki/List_of_newspapers_in_the_United_States

----------------------------------------
</details>

## 3. Test HTTP requests with Header field 'Range' to Web Server.

<details><summary>Details</summary>

1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
1.1. https://stackoverflow.com/questions/40691996/python-requests-http-range-not-working
2. Count length
2.1. https://stackoverflow.com/questions/7585435/best-way-to-convert-string-to-bytes-in-python-3
2.2. https://docs.python.org/3/library/functions.html#func-bytes
3. `curl -I <URL>`
3.1. https://curl.se/docs/manpage.html#-I
3.2. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges
4. `curl -r <Range> <URL>`
4.1. https://curl.se/docs/manpage.html#-r
4.2. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range
4.3. https://rwserve.readwritetools.com/range.blue
4.4. https://tools.ietf.org/id/draft-ietf-http-range-retrieval-00.txt

----------------------------------------
</details>

## 4. List of Search Engines bot User-Agent

1. https://www.keycdn.com/blog/web-crawlers
2. https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers
3. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
4. `Mozilla/5.0`
4.1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox
5. `Gecko`
5.1. https://developer.mozilla.org/en-US/docs/Glossary/Gecko
6. `curl -L -H "User-Agent: V4EXbot/2022" <URL> -o <Filename>`

----------------------------------------
